[package]
name = "rust_binance"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["full"] }
binance-rs-async = "1.3"
rust_decimal = "1.33"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
parking_lot = { version = "0.12", features = ["serde"]}